name = "meu-projeto"
type = "javascript" # ou "webpack", "javascript" dependendo do setup
account_id = "SEU_ACCOUNT_ID" # obtido no painel Cloudflare
compatibility_date = "2024-11-06"
compatibility_flags = ["nodejs_compat"]
